export const FETCH_PHOTOS = "FETCH_PHOTOS"
export const ADD_PHOTOS = "ADD_PHOTOS"
export const FETCH_SUGGESTIONS = "FETCH_SUGGESTIONS"
export const ADD_SUGGESTIONS = "ADD_SUGGESTIONS"
export const ADD_SUGGESTION_PIN = "ADD_SUGGESTION_PIN"

